### ISSUE TITLE
Audio does not work after re-imaging/installing voice kit 2 Pi Zero (Original HW)

### ISSUE THREAD

**Issue by lestig** [google/aiyprojects-raspbian#515]
I have spent a few hours chasing this one without luck, so decided to ask for some guidance...

**Problem**
'Do not have sound card error message' - after reimaging the SD card and installing with the latest build available.

- I am using the original hardware.  AIY voice kit v2.0
- BUILD: [(2018-08-03)](https://github.com/google/aiyprojects-raspbian/releases/tag/v20180803).
- Tried adding a line to the config.txt file 'dtoverlay' below.  But it should not apply in my case - either way it did not work

**Error/Details**
- When running the check audio script I get the following error message (I have a voice bonnet so I don't think the suggestion below applies):

_You do not have any sound cards installed. Please check that AIY sound card is
properly connected.
For some Voice HATs (not Voice Bonnets!) you need to add the following line
to /boot/config.txt:
dtoverlay=googlevoicehat-soundcard
To do that simply run from a separate terminal:
echo "dtoverlay=googlevoicehat-soundcard" | sudo tee -a /boot/config.txt
Press Enter to close..._

**Any help will be appreciated!**

**Comment by manoj7410** [comment]
@tibre Can you paste the complete error ? And can you also share the output of the command "lsmod".

**Comment by lestig** [comment]
I made it work in a couple of ways:

1. I installed the 2018-04-13 build and it worked without issues.  
2. Installed a fresh copy of raspbian (NOOBS v2_9_0) and followed the HACKING.md instructions.  There was a problem with the sound card driver enumeration Index (bcm2835 ALSA was enumerated first, Voicebonnet second).  Commented out '#dtparam=audio=on' on /boot/config.txt and that solved it (Dimitry's suggestion)

**So** I don't know why 2018-08-03 does not work with the kit right off the bat, but thanks for following up.

**Comment by lestig** [comment]
> @tibre Can you paste the complete error ? And can you also share the output of the command "lsmod".

Well, with #2 above (Fresh copy of rasbian and following HACKING) I am able to test speaker and record but when trying the assistant_grpc_demo I get an error message:

Failed to import google.cloud.speech. Try:
    env/bin/pip install -r requirements.txt

I am not running a virtual environment.  Also, just replying to your previous ask here the lsmod output of my current configuration:
_--------
Module                  Size  Used by
fuse                   92909  3
rfcomm                 37969  4
bnep                   11981  2
hci_uart               27218  1
btbcm                   8248  1 hci_uart
serdev                  9370  1 hci_uart
bluetooth             366847  29 hci_uart,bnep,btbcm,rfcomm
ecdh_generic           17649  1 bluetooth
aiy_adc                 4690  0
gpio_aiy_io             4226  0
evdev                  11644  1
industrialio           63573  1 aiy_adc
pwm_aiy_io              5084  0
leds_ktd202x            7349  0
aiy_io_i2c              6848  3 aiy_adc,gpio_aiy_io,pwm_aiy_io
brcmfmac              273230  0
brcmutil                9114  1 brcmfmac
cfg80211              542242  1 brcmfmac
rfkill                 21476  6 bluetooth,cfg80211
snd_aiy_voicebonnet     5048  3
rt5645                 88615  2 snd_aiy_voicebonnet
rl6231                  2904  1 rt5645
snd_soc_bcm2835_i2s     7385  2
regmap_mmio             3874  1 snd_soc_bcm2835_i2s
snd_soc_core          178253  3 snd_aiy_voicebonnet,rt5645,snd_soc_bcm2835_i2s
snd_compress            9956  1 snd_soc_core
snd_pcm_dmaengine       5370  1 snd_soc_core
i2c_bcm2835             6465  0
snd_pcm                89558  4 snd_pcm_dmaengine,rt5645,snd_soc_bcm2835_i2s,snd_soc_core
snd_timer              22428  1 snd_pcm
snd                    60154  10 snd_compress,snd_timer,snd_soc_core,snd_pcm
uio_pdrv_genirq         3718  0
uio                     9901  1 uio_pdrv_genirq
fixed                   3033  0
pwm_soft               25457  0
i2c_dev                 6674  0
ip_tables              12427  0
x_tables               22130  1 ip_tables
ipv6                  397278  30_

**Comment by dmitriykovalev** [comment]
@tibre Can you please confirm that you used 2018-08-03 image with the VisionBonnet (v2.0) and sound check failed with `You do not have any sound cards installed` message right after the boot? It's pretty weird, especially if the same sound check works fine with 2018-04-13 build. 

Can you please also attach the output of `dmesg` command right after the check fails?

**Comment by lestig** [comment]
@dmitriykovalev Yes, that's the file:

**MD5**
MD5 hash of aiyprojects-2018-08-03.img.xz:
386dafcc76c8539990e75e374f33b513
CertUtil: -hashfile command completed successfully.

**VoiceBonnet (v2.0)** not VisionBonnet
![voice_bonnet](https://user-images.githubusercontent.com/4122785/47961421-e9468900-dfc7-11e8-9f8d-884fe33873c7.JPG)

I will reimage an SD with that build and will give you details.  Now, the only difference that I recall and that might be creating the problem is updates.  When installing 08-03, updates are an option and they are executed right away compared to 04-13.

**Comment by dmitriykovalev** [comment]
@tibre Sorry, right, that was a typo, VoiceBonnet :)  Please do not install any updates for now (we are working to fix this) That could be exactly the source of problems.

**Comment by lestig** [comment]
@dmitriykovalev Thanks for the update.  
That said, any ideas.suggestions how to move forward pass this message (when trying latest Noobe's install+HACKING instructions):

_Failed to import google.cloud.speech. Try:
env/bin/pip install -r requirements.txt_

**Comment by dmitriykovalev** [comment]
@tibre That's weird, how do you run cloud speech example, what's the command line?  This error message is obsolete but still shouldn't happen. Are you using `python3`?

**Comment by lestig** [comment]
@dmitriykovalev It seemed odd to me as well.  Yes, I am executing using python3 as usual.  To recap:

1. Installed latest Rasbian build (Noobe 2.9.0)
2. Followed Hacking.md instructions _(Had a problem as bcm2835 ALSA drivers where enumerated 1st)__
3. Ensured only voicebonnet is enumerated and active - _commmented out 'dtparam=audio... _ 
4. Confirmed everything is functioning properly.  Can access sound card, record, play without issues...
5. **Ran assistant_grpc_demo script and got that error message...**

_I tried a number of things to no avail.  I even bypassed the call in the _speech script (if I remember correctly...) but that created other issues._

**Comment by dmitriykovalev** [comment]
@tibre Have you installed https://pypi.org/project/google-cloud-speech/ library?

```bash
sudo pip3 install google-cloud-speech
```

**Comment by andrewtvuong** [comment]
I've noticed certain programs no longer produce sound from 4-13-18 to 8-3-18. I'm not certain but it seems the culprit has something to do with switching to PulseAudio from ALSA? I don't know much about the subject.

**Comment by andrewtvuong** [comment]
> @tibre Have you installed https://pypi.org/project/google-cloud-speech/ library?
> 
> ```shell
> sudo pip3 install google-cloud-speech
> ```

wow that's awesome! I'm new to the subject, but is there a way to have its model so I can run on device? like a small subset that recognizes common commands.

**Comment by dmitriykovalev** [comment]
@andrewtvuong Yes, we switched to PulseAudio (it still uses ALSA underneath). Which programs don't work for you?

**Comment by andrewtvuong** [comment]
@dmitriykovalev Not part of AIY or Rasbian images:

Raspotify - https://github.com/dtcooper/raspotify
built from Librespot library for https://github.com/librespot-org/librespot

**Comment by mdbrewer** [comment]
I am having the same issue with two out of the box AIY kits, using the 2018-11-16 build. 

You do not have any sound cards installed. Please check that AIY sound card is
properly connected.

For some Voice HATs (not Voice Bonnets!) you need to add the following line
to /boot/config.txt:

dtoverlay=googlevoicehat-soundcard

To do that simply run from a separate terminal:

echo "dtoverlay=googlevoicehat-soundcard" | sudo tee -a /boot/config.txt
Press Enter to close...


I have updated the firmware, APT-upgrade, and checked the help forum. Still no go.

**Comment by mdbrewer** [comment]
I loaded AIY Kits Release 2018-04-13 and things work. I am not sure the difference.

**Comment by TimeDoctor** [comment]
this issue has been going on since November? I also have the issue with "You do not have any sound cards installed. "

**Comment by NuclearMonster** [comment]
I have this "You do not have any sound cards installed." issue as well with the check_audio script on the v2 pi zero kit

**Comment by nathanjnorris** [comment]
Hi, I'm having the same issues as everyone else. I have the AIY Voice Kit 2.0 and when I run cat /etc/aiyprojects.info this is the output:
`Build info: Fri Nov 16 08:31:49 UTC 2018 @ c5f367a`

Here's the dmesg output after check_audio fails:
`pi@raspberrypi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.79+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 Sun Nov 4 17:28:08 GMT 2018
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x17400000
[    0.000000] On node 0 totalpages: 98304
[    0.000000] free_area_init_node: node 0, pgdat c09c6650, node_mem_map d7c8a000
[    0.000000]   Normal zone: 864 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 98304 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 97440
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:2B:5F:CD vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=8a3809b7-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 370264K/393216K available (6435K kernel code, 588K rwdata, 1992K rodata, 444K init, 673K bss, 14760K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xd8800000 - 0xff800000   ( 624 MB)
                   lowmem  : 0xc0000000 - 0xd8000000   ( 384 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0xc0008000 - 0xc0650e90   (6436 kB)
                     .init : 0xc08cf000 - 0xc093e000   ( 444 kB)
                     .data : 0xc093e000 - 0xc09d1000   ( 588 kB)
                      .bss : 0xc09d6904 - 0xc0a7eeac   ( 674 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 24117 entries in 71 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000034] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000065] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000149] bcm2835: system timer (irq = 27)
[    0.000722] Console: colour dummy device 80x30
[    0.000748] console [tty1] enabled
[    0.000783] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060302] pid_max: default: 32768 minimum: 301
[    0.060795] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.060816] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062101] Disabling memory control group subsystem
[    0.062258] CPU: Testing write buffer coherency: ok
[    0.063384] Setting up static identity map for 0x8200 - 0x8238
[    0.064602] devtmpfs: initialized
[    0.074172] random: get_random_u32 called from bucket_table_alloc+0x88/0x1c4 with crng_init=0
[    0.075158] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.075529] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.075557] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.076881] pinctrl core: initialized pinctrl subsystem
[    0.078222] NET: Registered protocol family 16
[    0.081301] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.087634] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.087651] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.087769] Serial: AMBA PL011 UART driver
[    0.090728] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.091469] uart-pl011 20201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.130162] bcm2835-dma 20007000.dma: DMA legacy API manager at d880d000, dmachans=0x1
[    0.132506] SCSI subsystem initialized
[    0.132738] usbcore: registered new interface driver usbfs
[    0.132855] usbcore: registered new interface driver hub
[    0.133059] usbcore: registered new device driver usb
[    0.140817] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-11-04 16:35
[    0.142909] clocksource: Switched to clocksource timer
[    0.231684] VFS: Disk quotas dquot_6.6.0
[    0.231806] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.232091] FS-Cache: Loaded
[    0.232411] CacheFiles: Loaded
[    0.249587] NET: Registered protocol family 2
[    0.250787] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.250876] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.250971] TCP: Hash tables configured (established 4096 bind 4096)
[    0.251123] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.251154] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.251499] NET: Registered protocol family 1
[    0.252213] RPC: Registered named UNIX socket transport module.
[    0.252225] RPC: Registered udp transport module.
[    0.252231] RPC: Registered tcp transport module.
[    0.252237] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.254351] hw perfevents: no irqs for PMU, sampling events not supported
[    0.254428] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    0.258074] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.270086] FS-Cache: Netfs 'nfs' registered for caching
[    0.271402] NFS: Registering the id_resolver key type
[    0.271459] Key type id_resolver registered
[    0.271466] Key type id_legacy registered
[    0.271494] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.276274] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.276682] io scheduler noop registered
[    0.276696] io scheduler deadline registered (default)
[    0.277220] io scheduler cfq registered
[    0.277235] io scheduler mq-deadline registered
[    0.277243] io scheduler kyber registered
[    0.279518] BCM2708FB: allocated DMA memory 57500000
[    0.279581] BCM2708FB: allocated DMA channel 0 @ d880d000
[    0.287648] Console: switching to colour frame buffer device 82x26
[    0.295515] bcm2835-rng 20104000.rng: hwrng registered
[    0.295733] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.296718] vc-sm: Videocore shared memory driver
[    0.297285] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    0.315971] brd: module loaded
[    0.327953] loop: module loaded
[    0.327975] Loading iSCSI transport class v2.0-870.
[    0.328801] usbcore: registered new interface driver smsc95xx
[    0.328834] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.356908] dwc_otg 20980000.usb: base=0xf0980000
[    0.557323] Core Release: 2.80a
[    0.557341] Setting default values for core params
[    0.557382] Finished setting default values for core params
[    0.757712] Using Buffer DMA mode
[    0.757727] Periodic Transfer Interrupt Enhancement - disabled
[    0.757732] Multiprocessor Interrupt Enhancement - disabled
[    0.757744] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.757842] Dedicated Tx FIFOs mode
[    0.758694] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xd7514000 dma = 0x57514000 len=9024
[    0.758723] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.758735] dwc_otg: Microframe scheduler enabled
[    0.758899] WARN::hcd_init_fiq:459: FIQ on core 0 at 0xc049c7ac
[    0.758914] WARN::hcd_init_fiq:460: FIQ ASM at 0xc049ca88 length 36
[    0.758941] WARN::hcd_init_fiq:486: MPHI regs_base at 0xf0006000
[    0.759025] dwc_otg 20980000.usb: DWC OTG Controller
[    0.759089] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
[    0.759162] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
[    0.759216] Init: Port Power? op_state=1
[    0.759222] Init: Power Port (0)
[    0.759630] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.759648] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.759659] usb usb1: Product: DWC OTG Controller
[    0.759668] usb usb1: Manufacturer: Linux 4.14.79+ dwc_otg_hcd
[    0.759679] usb usb1: SerialNumber: 20980000.usb
[    0.760782] hub 1-0:1.0: USB hub found
[    0.760877] hub 1-0:1.0: 1 port detected
[    0.761796] dwc_otg: FIQ enabled
[    0.761807] dwc_otg: NAK holdoff enabled
[    0.761813] dwc_otg: FIQ split-transaction FSM enabled
[    0.761832] Module dwc_common_port init
[    0.762334] usbcore: registered new interface driver usb-storage
[    0.762770] mousedev: PS/2 mouse device common for all mice
[    0.762829] IR NEC protocol handler initialized
[    0.762836] IR RC5(x/sz) protocol handler initialized
[    0.762841] IR RC6 protocol handler initialized
[    0.762846] IR JVC protocol handler initialized
[    0.762852] IR Sony protocol handler initialized
[    0.762857] IR SANYO protocol handler initialized
[    0.762862] IR Sharp protocol handler initialized
[    0.762867] IR MCE Keyboard/mouse protocol handler initialized
[    0.762872] IR XMP protocol handler initialized
[    0.764218] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.764753] bcm2835-cpufreq: min=700000 max=1000000
[    0.765349] sdhci: Secure Digital Host Controller Interface driver
[    0.765360] sdhci: Copyright(c) Pierre Ossman
[    0.765988] mmc-bcm2835 20300000.mmc: could not get clk, deferring probe
[    0.766606] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    0.766788] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.767292] ledtrig-cpu: registered to indicate activity on CPUs
[    0.767436] hidraw: raw HID events driver (C) Jiri Kosina
[    0.767696] usbcore: registered new interface driver usbhid
[    0.767705] usbhid: USB HID core driver
[    0.768657] vchiq: vchiq_init_state: slot_zero = d7580000, is_master = 0
[    0.770665] [vc_sm_connected_init]: start
[    0.780063] [vc_sm_connected_init]: end - returning 0
[    0.781006] Initializing XFRM netlink socket
[    0.781068] NET: Registered protocol family 17
[    0.781244] Key type dns_resolver registered
[    0.783180] registered taskstats version 1
[    0.791338] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.791474] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.794595] mmc-bcm2835 20300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.794614] mmc-bcm2835 20300000.mmc: DMA channel allocated
[    0.856409] sdhost: log_buf @ d7513000 (57513000)
[    0.893882] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.895535] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.897180] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.900109] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.927109] random: fast init done
[    0.942970] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.964370] of_cfs_init
[    0.964511] of_cfs_init: OK
[    0.965476] Waiting for root device PARTUUID=8a3809b7-02...
[    1.010705] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.013281] mmc0: new high speed SDHC card at address 59b4
[    1.014164] mmcblk0: mmc0:59b4 SD    7.36 GiB
[    1.016492]  mmcblk0: p1 p2
[    1.030404] mmc1: new high speed SDIO card at address 0001
[    1.037656] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.037749] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.039108] devtmpfs: mounted
[    1.041580] Freeing unused kernel memory: 444K
[    1.041589] This architecture does not have kernel memory protection.
[    1.532180] systemd[1]: System time before build time, advancing clock.
[    1.702345] NET: Registered protocol family 10
[    1.704264] Segment Routing with IPv6
[    1.717486] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.742721] random: systemd: uninitialized urandom read (16 bytes read)
[    1.751800] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.752848] systemd[1]: Detected architecture arm.
[    1.754679] systemd[1]: Set hostname to <raspberrypi>.
[    1.833877] random: systemd: uninitialized urandom read (16 bytes read)
[    2.111580] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    2.954808] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.956002] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.956932] systemd[1]: Listening on udev Control Socket.
[    2.958861] systemd[1]: Created slice System Slice.
[    2.965543] systemd[1]: Mounting POSIX Message Queue File System...
[    2.969107] systemd[1]: Created slice User and Session Slice.
[    2.969606] systemd[1]: Reached target Slices.
[    3.472666] i2c /dev entries driver
[    5.329041] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    5.894632] systemd-journald[78]: Received request to flush runtime journal from PID 1
[    9.293326] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    9.314564] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    9.314982] usbcore: registered new interface driver brcmfmac
[    9.759499] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    9.760644] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14 
[   14.088554] uart-pl011 20201000.serial: no DMA platform data
[   17.744209] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   18.766563] Bluetooth: Core ver 2.22
[   18.766670] NET: Registered protocol family 31
[   18.766678] Bluetooth: HCI device and connection manager initialized
[   18.766703] Bluetooth: HCI socket layer initialized
[   18.766716] Bluetooth: L2CAP socket layer initialized
[   18.766760] Bluetooth: SCO socket layer initialized
[   18.824129] Bluetooth: HCI UART driver ver 2.3
[   18.824145] Bluetooth: HCI UART protocol H4 registered
[   18.824150] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   18.863087] Bluetooth: HCI UART protocol Broadcom registered
[   20.183077] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   20.183090] Bluetooth: BNEP filters: protocol multicast
[   20.183117] Bluetooth: BNEP socket layer initialized
[   20.292753] random: crng init done
[   20.292773] random: 7 urandom warning(s) missed due to ratelimiting
[   20.300110] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   20.300129] brcmfmac: power management disabled
[   20.391074] Bluetooth: RFCOMM TTY layer initialized
[   20.391110] Bluetooth: RFCOMM socket layer initialized
[   20.391145] Bluetooth: RFCOMM ver 1.11
[   22.184237] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   39.791467] fuse init (API version 7.26)`

Any help with this bug would be much appreciated :)

**Comment by mongonta0716** [comment]
Hi,

I think that the cause is that the driver disappears by updating firmware.
Try the following commands.

cd /usr/src
sudo dkms install aiy-1.1
sudo dkms install aiy-vision-1.1
sudo dkms install aiy-voicebonnet-soundcard-1.0
sudo dkms install leds-ktd202x-1.1
sudo dkms install pwm-soft-1.1
sudo reboot

The name of the driver changes depending on the AIY Kits OS version, check with 'ls /usr/src'

**Comment by NuclearMonster** [comment]
> sudo dkms install aiy-voicebonnet-soundcard-1.0

thanks, this one did it for my project, once I made it 1.1 sound worked again. Oddly, all the other modules that were useful for the voice kit were already installed!

**Comment by andrewtvuong** [comment]
> Hi,
> 
> I think that the cause is that the driver disappears by updating firmware.
> Try the following commands.
> 
> cd /usr/src
> sudo dkms install aiy-1.1
> sudo dkms install aiy-vision-1.1
> sudo dkms install aiy-voicebonnet-soundcard-1.0
> sudo dkms install leds-ktd202x-1.1
> sudo dkms install pwm-soft-1.1
> sudo reboot
> 
> The name of the driver changes depending on the AIY Kits OS version, check with 'ls /usr/src'

Hi @mongonta0716 , thanks for sharing.

```
Error! DKMS tree already contains: aiy-voicebonnet-soundcard-1.0
You cannot add the same module/version combo more than once.
```
I'm getting this message for every command you listed. Should I uninstall and reinstall? If so I'm not familiar and don't want to mess up dependencies or some kind of problem, would it be safe to uninstall and how? rm -rf?

**Comment by mongonta0716** [comment]
Hi @andrewtvuong 

Sorry I couldn't help you. 
If there is a driver it is a different case from me.I have written something unrelated to this Issue.In my case,the following command was executed and the driver was built.
``
sudo dkms install aiy-voicebonnet-soundcard-1.0
``

My environment
Google AIY Voice Kit V2
BUILD: 2018-11-16 and apt-upgrade
firmware:4.14.79+

**Comment by mdbrewer** [comment]
> Hi,
> 
> I think that the cause is that the driver disappears by updating firmware.
> Try the following commands.
> 
> cd /usr/src
> sudo dkms install aiy-1.1
> sudo dkms install aiy-vision-1.1
> sudo dkms install aiy-voicebonnet-soundcard-1.0
> sudo dkms install leds-ktd202x-1.1
> sudo dkms install pwm-soft-1.1
> sudo reboot
> 
> The name of the driver changes depending on the AIY Kits OS version, check with 'ls /usr/src'

After a fresh install of 11-16 image, an update, then running the above driver installs, and it works.

**Comment by remzioten** [comment]
> Hi,
> 
> I think that the cause is that the driver disappears by updating firmware.
> Try the following commands.
> 
> cd /usr/src
> sudo dkms install aiy-1.1
> sudo dkms install aiy-vision-1.1
> sudo dkms install aiy-voicebonnet-soundcard-1.0
> sudo dkms install leds-ktd202x-1.1
> sudo dkms install pwm-soft-1.1
> sudo reboot
> 
> The name of the driver changes depending on the AIY Kits OS version, check with 'ls /usr/src'

This solved for me. Thanks

**Comment by jreyn88** [comment]
Why would an image created by starting with AIY Voice then adding Shairport-Sync and Homebridge with V2 voicebonnet, work in another 3b but not the Zero WH that came with the voicebonnet? I tried the above steps but it recognizes a Google soundcard in the Zero instead of the voicebonnet in both 3b's.

**Comment by andrewtvuong** [comment]
@jreyn88 Very strange, but I had a lot of problems on 3A+, that resolved itself after several reimages. Keep downloading and changing SD cards, update etcher. I don’t understand the reasons, but all my problems are gone.

**Comment by juanfonsecasolis** [comment]
I downloaded the 2018-08-03 build and ended up repeating timbre's experience. Could you remove that build to avoid that other people experience the same problems, please?

**Comment by gitty323** [comment]
I am having this same issue on the 2019-11-13 build, should I just flash the older version?

Edit: Nevermind.. I had to reboot after adding dtoverlay=googlevoicehat-soundcard to the config. It works now.

**Comment by rudjer** [comment]
I'm having this same issue on a V2 voice bonnet with the 2019-11-13 build running:  
~/AIY-projects-python/checkpoints $ python3 check_audio.py
I tried adding to /boot/config.txt and rebooting, but that didn't help, perhaps not
surprisingly given that the message only implies this might help for V1.

This seems to have been a update issue.  I reinstalled a fresh flash of the 2019-11-13
build, and skipped the update step of the installation, and now assistant and other
sound card issues are resolved.

**Comment by diegoshh** [comment]
Hi, I have a problem with audio, after intalling aiy-2019-11-13.img.xz on the raspberrypi the icon for the speaker on the navigation bar dissaperas, also I have that same message (you so not have any sound card installed. Please check that AIY sound card is properly connected.

I wanted to use the speakers of a samsung TV, but it didnt work, so I connected a speaker in the AUX and it still doesnt work when I check the audio. Help please!

**Comment by diegoshh** [comment]
by the way Im using a raspberry pi 4
